// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.shengsiyuan.netty.grpc;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.shengsiyuan.netty.grpc.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.shengsiyuan.netty.grpc.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<com.shengsiyuan.netty.grpc.StudentResponse> 
      getStudentResponseList();
  /**
   * <code>repeated .com.shengsiyuan.netty.grpc.StudentResponse studentResponse = 1;</code>
   */
  com.shengsiyuan.netty.grpc.StudentResponse getStudentResponse(int index);
  /**
   * <code>repeated .com.shengsiyuan.netty.grpc.StudentResponse studentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <code>repeated .com.shengsiyuan.netty.grpc.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<? extends com.shengsiyuan.netty.grpc.StudentResponseOrBuilder> 
      getStudentResponseOrBuilderList();
  /**
   * <code>repeated .com.shengsiyuan.netty.grpc.StudentResponse studentResponse = 1;</code>
   */
  com.shengsiyuan.netty.grpc.StudentResponseOrBuilder getStudentResponseOrBuilder(
      int index);
}
